insert into university (universityID, uni_name, uni_address) values (1, 'Universidad Metropolitana', '82 Milwaukee Plaza');
insert into university (universityID, uni_name, uni_address) values (2, 'Rajitlal Institute of Technology & Health Sciences (RITHS)', '0 5th Trail');
insert into university (universityID, uni_name, uni_address) values (3, 'The College of Santa Fe', '473 Sullivan Circle');
insert into university (universityID, uni_name, uni_address) values (4, 'Algonquin College', '3 Schiller Place');
insert into university (universityID, uni_name, uni_address) values (5, 'Gyeongju University', '401 Sachs Court');
insert into university (universityID, uni_name, uni_address) values (6, 'University of North Alabama', '2 Haas Place');
insert into university (universityID, uni_name, uni_address) values (7, 'Methodist College', '967 Cascade Alley');
insert into university (universityID, uni_name, uni_address) values (8, 'University of Connecticut at Avery Point', '61984 Parkside Hill');
insert into university (universityID, uni_name, uni_address) values (9, 'Institut Supérieur d''Agriculture Rhone-Alpes', '625 Clyde Gallagher Hill');
insert into university (universityID, uni_name, uni_address) values (10, 'École nationale d''administration publique, Université du Québec', '5 Independence Terrace');
insert into university (universityID, uni_name, uni_address) values (11, 'Kyushu University', '44862 Bay Place');
insert into university (universityID, uni_name, uni_address) values (12, 'Alaska Bible College', '61 Schurz Point');
insert into university (universityID, uni_name, uni_address) values (13, 'Dalian University', '54 Cherokee Circle');
insert into university (universityID, uni_name, uni_address) values (14, 'Universidad Experimental Felix Adam', '1075 Londonderry Lane');
insert into university (universityID, uni_name, uni_address) values (15, 'Université de Bouaké', '5 Tomscot Park');
insert into university (universityID, uni_name, uni_address) values (16, 'Universitas Bung Hatta', '3 Lunder Crossing');
insert into university (universityID, uni_name, uni_address) values (17, 'Universidad Nacional Autonoma de Nicaragua', '7 Russell Street');
insert into university (universityID, uni_name, uni_address) values (18, 'Washington University in St. Louis', '04 Tony Road');
insert into university (universityID, uni_name, uni_address) values (19, 'Kashan University', '8687 Little Fleur Avenue');
insert into university (universityID, uni_name, uni_address) values (20, 'Pokhara University', '7 Birchwood Street');
insert into university (universityID, uni_name, uni_address) values (21, 'Sekolah Tinggi Akuntansi Negara (STAN)', '304 Bartelt Point');
insert into university (universityID, uni_name, uni_address) values (22, 'Academy of the Ministry of Internal Affairs of the Republic of Belarus', '2 Green Ridge Way');
insert into university (universityID, uni_name, uni_address) values (23, 'Universitas Sumatera Utara', '6814 Derek Junction');
insert into university (universityID, uni_name, uni_address) values (24, 'Governors State University', '444 Boyd Park');
insert into university (universityID, uni_name, uni_address) values (25, 'Swinburne University of Technology, Sarawak Campus', '06 Village Place');
insert into university (universityID, uni_name, uni_address) values (26, 'Jimma University', '63 Wayridge Alley');
insert into university (universityID, uni_name, uni_address) values (27, 'Bridgewater College', '3554 Northfield Circle');
insert into university (universityID, uni_name, uni_address) values (28, 'Eelo American University', '429 Crownhardt Alley');
insert into university (universityID, uni_name, uni_address) values (29, 'Indira Gandhi Institute of Development and Research', '35171 Shoshone Crossing');
insert into university (universityID, uni_name, uni_address) values (30, 'Ecole Supérieure de Commerce de Reims', '47830 Cherokee Point');
insert into university (universityID, uni_name, uni_address) values (31, 'Kurume Institute of Technology', '90595 Crest Line Way');
insert into university (universityID, uni_name, uni_address) values (32, 'Knightsbridge University', '758 Troy Parkway');
insert into university (universityID, uni_name, uni_address) values (33, 'Pontificio Istituto Orientale', '8270 Kingsford Place');
insert into university (universityID, uni_name, uni_address) values (34, 'Fred Hutchinson Cancer Research Center', '3133 High Crossing Street');
insert into university (universityID, uni_name, uni_address) values (35, 'Phillips-Universität Marburg', '5 Victoria Circle');
insert into university (universityID, uni_name, uni_address) values (36, 'Aristotle University of Thessaloniki', '47 Columbus Avenue');
insert into university (universityID, uni_name, uni_address) values (37, 'Guru Jambeshwar University', '86 Blue Bill Park Court');
insert into university (universityID, uni_name, uni_address) values (38, 'Kyoritsu Woman''s University', '0 Almo Parkway');
insert into university (universityID, uni_name, uni_address) values (39, 'West Virginia University Institute of Technology', '21 Schiller Terrace');
insert into university (universityID, uni_name, uni_address) values (40, 'University of Applied Sciences of Moldova', '4382 Loeprich Circle');
insert into university (universityID, uni_name, uni_address) values (41, 'Amber University', '8882 Beilfuss Place');
insert into university (universityID, uni_name, uni_address) values (42, 'Technical University of Kenya', '943 Tony Way');
insert into university (universityID, uni_name, uni_address) values (43, 'Alverno College', '48655 Paget Avenue');
insert into university (universityID, uni_name, uni_address) values (44, 'Poltava University of Consumer Cooperatives in Ukraine', '3 Prairieview Terrace');
insert into university (universityID, uni_name, uni_address) values (45, 'St. Andrew Georgian University', '8652 Cascade Road');
insert into university (universityID, uni_name, uni_address) values (46, 'Universiti Tunku Abdul Rahman', '47 Summerview Plaza');
insert into university (universityID, uni_name, uni_address) values (47, 'National University of Samoa', '61867 Stang Parkway');
insert into university (universityID, uni_name, uni_address) values (48, 'Rabindra Bharati University', '796 Buhler Point');
insert into university (universityID, uni_name, uni_address) values (49, 'University of Groningen', '75 Anzinger Plaza');
insert into university (universityID, uni_name, uni_address) values (50, 'Rand Graduate School of Policy Studies', '993 Tennyson Crossing');
insert into university (universityID, uni_name, uni_address) values (51, 'Jigjiga University', '6 Buena Vista Terrace');
insert into university (universityID, uni_name, uni_address) values (52, 'Korea National University of Arts', '1285 Caliangt Circle');
insert into university (universityID, uni_name, uni_address) values (53, 'Southern University Bangladesh', '26 Service Center');
insert into university (universityID, uni_name, uni_address) values (54, 'Arab Open University, Kuwait Branch', '89 Pearson Point');
insert into university (universityID, uni_name, uni_address) values (55, 'Ashesi University', '47141 Holmberg Crossing');
insert into university (universityID, uni_name, uni_address) values (56, 'Taoist College Singapore', '5 5th Road');
insert into university (universityID, uni_name, uni_address) values (57, 'University of Trnava', '49985 Twin Pines Alley');
insert into university (universityID, uni_name, uni_address) values (58, 'Deakin University', '969 Susan Alley');
insert into university (universityID, uni_name, uni_address) values (59, 'Matn University', '789 Chinook Place');
insert into university (universityID, uni_name, uni_address) values (60, 'Mount St. Clare College', '5833 Autumn Leaf Place');
insert into university (universityID, uni_name, uni_address) values (61, 'Université Shalom de Bunia', '3279 Michigan Court');
insert into university (universityID, uni_name, uni_address) values (62, 'Oduduwa University', '50726 Hollow Ridge Lane');
insert into university (universityID, uni_name, uni_address) values (63, 'Université Nancy II', '8993 Sommers Trail');
insert into university (universityID, uni_name, uni_address) values (64, 'Alkharj University', '48 Clove Park');
insert into university (universityID, uni_name, uni_address) values (65, 'Tuva State University', '848 Springview Circle');
insert into university (universityID, uni_name, uni_address) values (66, 'Western Bible College', '8390 Ridgeway Circle');
insert into university (universityID, uni_name, uni_address) values (67, 'Warnborough University', '875 Judy Trail');
insert into university (universityID, uni_name, uni_address) values (68, 'Ecole Normale Supérieure de Paris', '1 Beilfuss Pass');
insert into university (universityID, uni_name, uni_address) values (69, 'University of South Carolina', '89 Randy Road');
insert into university (universityID, uni_name, uni_address) values (70, 'Jaypee Institute of Information Technology', '4 Waubesa Park');
insert into university (universityID, uni_name, uni_address) values (71, 'University of Massachusetts at Amherst', '952 Swallow Junction');
insert into university (universityID, uni_name, uni_address) values (72, 'Royal University of Bhutan', '4 Mallory Parkway');
insert into university (universityID, uni_name, uni_address) values (73, 'Hodeidah University', '8 Continental Avenue');
insert into university (universityID, uni_name, uni_address) values (74, 'Universidad de Viña del Mar', '72605 Morrow Alley');
insert into university (universityID, uni_name, uni_address) values (75, 'Universidad Mayor', '8 Randy Point');
insert into university (universityID, uni_name, uni_address) values (76, 'Florida International University', '2 Kedzie Center');
insert into university (universityID, uni_name, uni_address) values (77, 'Danish Business Academy', '25964 Meadow Ridge Crossing');
insert into university (universityID, uni_name, uni_address) values (78, 'National Central University', '044 Vera Trail');
insert into university (universityID, uni_name, uni_address) values (79, 'Western States Chiropractic College', '704 Oak Valley Center');
insert into university (universityID, uni_name, uni_address) values (80, 'Nanjing Forestry University', '71 Crowley Place');
insert into university (universityID, uni_name, uni_address) values (81, 'Mohan Lal Sukhadia University', '615 Miller Parkway');
insert into university (universityID, uni_name, uni_address) values (82, 'Medical Academy in Warszawa', '11 Graceland Alley');
insert into university (universityID, uni_name, uni_address) values (83, 'Internationale Fachhochschule Aalen', '0 Green Ridge Park');
insert into university (universityID, uni_name, uni_address) values (84, 'University of Wisconsin - Whitewater', '9 Valley Edge Junction');
insert into university (universityID, uni_name, uni_address) values (85, 'Universitas Haluoleo', '45 Lakewood Gardens Drive');
insert into university (universityID, uni_name, uni_address) values (86, 'Shendi University', '852 Sugar Drive');
insert into university (universityID, uni_name, uni_address) values (87, 'Illinois School of Professional Psychology - Meadows Campus', '870 Orin Crossing');
insert into university (universityID, uni_name, uni_address) values (88, 'Shanghai Jiaotong University', '30869 Paget Crossing');
insert into university (universityID, uni_name, uni_address) values (89, 'University of Queensland', '17 Corben Crossing');
insert into university (universityID, uni_name, uni_address) values (90, 'Latvian Academy of Arts', '95 Rutledge Way');
insert into university (universityID, uni_name, uni_address) values (91, 'Tohoku College of Pharmacy', '489 Alpine Plaza');
insert into university (universityID, uni_name, uni_address) values (92, 'Warnborough University', '6686 Hanson Alley');
insert into university (universityID, uni_name, uni_address) values (93, 'Royal Danish School of Educational Sciences', '998 Anzinger Lane');
insert into university (universityID, uni_name, uni_address) values (94, 'Buddhist Acamedy of China', '256 Oneill Point');
insert into university (universityID, uni_name, uni_address) values (95, 'Madurai Kamaraj University', '3481 Acker Lane');
insert into university (universityID, uni_name, uni_address) values (96, 'University of Texas Health Center at Tyler', '818 Luster Place');
insert into university (universityID, uni_name, uni_address) values (97, 'Pennsylvania State University at Erie - Behrend College', '99 Drewry Road');
insert into university (universityID, uni_name, uni_address) values (98, 'Knightsbridge University', '47338 Ruskin Alley');
insert into university (universityID, uni_name, uni_address) values (99, 'Komsomolsk-on-Amur State Technical University', '53 Arkansas Parkway');
insert into university (universityID, uni_name, uni_address) values (100, 'Western States Chiropractic College', '9 Mallory Lane');
